<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<EnableNetAnalyzers>true</EnableNetAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<AnalysisLevel>latest-Recommended</AnalysisLevel>
	</PropertyGroup>

	<PropertyGroup>
		<SolutionDir>$(MSBuildThisFileDirectory)</SolutionDir>
		<SourceDir>$(SolutionDir)src/</SourceDir>

		<LibsDir>$(SolutionDir)lib/</LibsDir>
		<AssemblySearchPaths>
			$(AssemblySearchPaths);
			$(LibsDir);
		</AssemblySearchPaths>

		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json;
			https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
	</PropertyGroup>

	<ItemDefinitionGroup>
		<Reference Private="false" />
		<ProjectReference Private="false" />
		<PackageReference PrivateAssets="all" />
	</ItemDefinitionGroup>

	<PropertyGroup>
		<PolyArgumentExceptions>true</PolyArgumentExceptions>
		<PolyStringInterpolation>true</PolyStringInterpolation>
	</PropertyGroup>
	<ItemGroup>
		<!-- NOTE: Copy/symlink these from Managed/ to lib/ -->
		<Reference Include="Assembly-CSharp"           Publicize="true" />
		<Reference Include="Assembly-CSharp-firstpass" Publicize="true" />
		<Reference Include="MoonSharp.Interpreter" />
		<Reference Include="Utilities" />
		<Reference Include="com.rlabrecque.steamworks.net.dll" />

		<PackageReference Include="BepInEx.Analyzers"                  Version="1.*" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.*" />
		<PackageReference Include="BepInEx.Core"                       Version="5.*" />
		<PackageReference Include="BepInEx.PluginInfoProps"            Version="2.*" />
		<PackageReference Include="UnityEngine.Modules"                Version="6000.3.10" IncludeAssets="compile" />

		<PackageReference Include="Polyfill" Version="11.2.0" />
	</ItemGroup>

</Project>
