<Project>

	<Import Project="../../Configuration.props" />

	<PropertyGroup>
		<AssemblyName>edu.sos.unleashed</AssemblyName> <!-- #bug: not working -->
		<Product>Unleashed</Product>
		<Version>0.4.0</Version>

		<DefineConstants Condition=" '$(TRUE_ULTIMATE_POWER)' != '0' ">$(DefineConstants);TRUE_ULTIMATE_POWER;</DefineConstants>
		<DefineConstants Condition=" '$(DEBUG_COMPAT)' == '1' ">$(DefineConstants);DEBUG_COMPAT;</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="BannedSymbols.txt" />
		<PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

</Project>
